name             'nginx_proxy'
maintainer       'Gabe Enslein'
maintainer_email 'genslein16@hotmail.com'
license          'All rights reserved'
description      'Installs/Configures new nginx proxy'
long_description 'Installs/Configures new nginx proxy to bing and weather'
version          '0.1.0'

depends 'apt',   '3.0.0'
depends 'nginx', '2.7.6'